config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'home#top'
  # コントローラーアクション
  	get 'home/about' => "home#about"
  	resources :users, only: [:show,:index,:edit,:update]
  	resources :books do
  		resource :favorites, only: [:create, :destroy]
  		resources :book_comments, only: [:create, :destroy]

  	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	# モデルの関係づけ
	belongs_to :user
	# book_comment 1:n
	has_many :book_comments, dependent: :destroy
	# favorite 1:n
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	# user 1:n
	belongs_to :user
	# book 1:n
	belongs_to :book
	# バリデーションチェック
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	# user
	belongs_to :user
	# book
	belongs_to :book
	# バリデーションチェック　いいね機能　１つの投稿につき１回のいいね
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # モデル関連づけ
  has_many :books, dependent: :destroy
  # gem refile
  attachment :profile_image, destroy: false
  # bookcomment 1:n
  has_many :book_comments, dependent: :destroy
  # favorite
  has_many :favorites, dependent: :destroy

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: { maximum: 20, minimum: 2}
  # validation introduction
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # deviseのストロングパラメータ
	before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン後のページ変遷の設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		# データを受け取ってsaveする commentはフォームから受け取る user_idとbook_idが欲しい
		# urlに:id含まれてないので:id使えない
		# リダイレクトで必要 @bookにいれるためにbook.findmの形
		# このアクションへのurlにbook_idと記載されているので:idでは無くbook_idを用いる
		# book_comment controlerだが別に他のモデルを使うこともできる
		@book = Book.find(params[:book_id])
		# コメントを受け取る
		@book_newbook = BookComment.new(book_comment_params)
		# user_id
		@book_newbook.user_id = current_user.id
		# showページなのえid 一つ持ってきている
		@book_newbook.book_id = @book.id
		# error
		if @book_newbook.save
				redirect_to request.referer
		else
				# book showページ表示のためのインスタンス変数
				#  bookd/showページでエラーを表示されるためにエラーを受けった値そのまま持っていく
    			# @book = Book.find(params[:id])
    			# user info
    			@user = @book.user
    			# new book からのオブジェクトが欲しい
    			@book_newbook = Book.new
    			# book_coment のフォーム
    			# @book_comment_new = BookComment.new
    			#  book commentの一覧 index
    			@book_comments = @book.book_comments.all
    			# レンダーメソッド フォルダの階層を書くので被災間違え注意する
				render "books/show"
		end
	end

	def destroy
		#データ取得してdestry　destroy正常に動く
		# リダイレクト先へのインスタンス変数
		@book = Book.find(params[:book_id])
		# モデルが正確に取ってくるように指定する
		book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
		book_comment.destroy
		redirect_to book_path(@book)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # booksでの表示も全てログインしている状態のみに制限する
  before_action :authenticate_user!

  def show
    # book show
    @book = Book.find(params[:id])
    # user info
    @user = @book.user
    # new book からのオブジェクトが欲しい
    @book_newbook = Book.new
    # book_coment のフォーム
    @book_comment_new = BookComment.new
    # book commentの一覧 index
    @book_comments = @book.book_comments.all
  end

  def index
    # user info はvireで生成している
    #books index
    @books = Book.all
    # new book
    @book = Book.new
    # user = current_user 効果ないので元に戻す

  end

  def create
    @book = Book.new(book_params)
    # 注意
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      #books index
      @books = Book.all
      # new book
      # @book = Book.new
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	# いいね機能のアクション作る
	def create
		# 値を受けとって変数の中にいれる savaしてリダイレクトする
		# user_id を取得
		# 別にviewhに変数を持っていかないのでローカル変数用いる
		@book = Book.find(params[:book_id])

		@favorite = Favorite.new
		# user_id
		@favorite.user_id = current_user.id
		# book_id を習得する
		@favorite.book_id = @book.id

		if @favorite.save
				redirect_to request.referer

		end
	end

	def destroy
		# 値受け取って destroy リダイレクト
		@book = Book.find(params[:book_id])
		# ただのidだけだと指定出来ない book_
		favorite = Favorite.find_by(params[:book_id])
		favorite.user_id = @book.user_id
		favorite.destroy
		redirect_to request.referer
		# なぜかうまくいかなかった r理由聞く
		# @book = Book.find(params[:book_id])
		# # カリキュラムみて作成した 持ってくるidを指定するために[id]と　[book_id]を使っt指定する
		# favorite = Favorite.find_by(id: params[:id]], book_id: params[:book_id])
		# favorite.destroy
		# redirect_to request.referer

	end

	# 今回 ストロングパラメータ使用しない
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :ensure_correct_user, only: [:update]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    # user controllerにおいてbook_modelは使用できない
    @book = Book.new
    # end足りてない
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user), notice: "You have updated user successfully."
      else
        render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :Title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Option %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<!-- error book.update 失敗時 -->
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this book from being saved:
	<% @book.errors.full_messages.each do |message| %>
		<ul>
			<li><%= message %></li>
		</ul>
	<% end %>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>

			<%= form_for(@book) do |f| %>
				<div class="field row">
					<%= f.label :Title %>
					<%= f.text_field :title, class: "col-xs-12 book_title" %>
				</div>

				<div class="field row">
					<%= f.label :Option %>
					<%= f.text_area :body, class: "col-xs-12 book_body" %>
				</div>

				<div class="actions row">
					<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>

			<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
			<%= link_to "Back", books_path, class: "back" %>

		</div>
		<div class="col-md-3"></div>

	</div>
</div>

app/views/books/index.html.erb
<!-- error message  book_create -->
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this book from being saved:
	<% @book.errors.full_messages.each do |message| %>
		<ul>
			<li><%= message %></li>
		</ul>
	<% end %>
<% end %>


<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<!-- いいね  いいねに自分が含まれているいないで考える-->
						<td>
							<% if book.favorited_by?(current_user) %>
								<%= link_to book_favorites_path(book), method: :delete do %>
									<!-- boostrap ハートマークを表示させる -->
									<span class="glyphicon glyphicon-heart" aria-hidden="true">
										<%= book.favorites.count %>
									</span>
								 	<!-- <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i> -->
								<% end %>
							<% else %>
								<%= link_to book_favorites_path(book), method: :post do %>
									<span class="glyphicon glyphicon-heart-empty" aria-hidden="true">
										<%= book.favorites.count %>
									</span>
									 <!-- <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i> -->

								<% end %>
							<% end %>
						</td>
						<!-- ここまでいいね -->
						<td>コメント数:<%= book.book_comments.count %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->
		</div>
	</div>
</div>

app/views/books/show.html.erb
<!-- erroe Message -->
<% if @book_newbook.errors.any? %>
	<% @book_newbook.errors.full_messages.each do |message| %>
		<ul>
			<li><%= message %></li>
		</ul>
	<% end %>
<%  end %>

 <div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>

			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book_newbook %>


		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
					<tr>
						<td>
							<!-- 画像 -->
							<%= link_to user_path(@book.user) do %>
								<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
								<!--　名前 -->
							<%= @book.user.name %>
							<% end %>
						</td>
						<!--book　タイトル  -->
						<td><%= link_to @book.title, book_path(@book) %></td>
						<!-- book body -->
						<td><%= @book.body %></td>

						<td>
								<!-- いいね機能 -->
								<% if @book.favorited_by?(current_user) %>
									<%= link_to book_favorites_path(@book), method: :delete do %>
										<!-- boostrap ハートマーク表示 -->
								 		<span class="glyphicon glyphicon-heart" aria-hidden="true">
								 			<%= @book.favorites.count %>
								 		</span>
								 		<!-- ここまで -->
									<% end %>
								<% else %>
									<%= link_to book_favorites_path(@book), method: :post do %>
									 	<!-- boostra@ ハートマーク表示 -->
									 	<span class="glyphicon glyphicon-heart-empty" aria-hidden="true">
									 		<%= @book.favorites.count %>
									 	</span>
									<% end %>
								<% end %>
								<!-- いいね機能 -->
						</td>
						<td>コメント数:<%= @book.book_comments.count %></td>
						<td>
							<!-- 投稿者のみがボタン表示 編集  -->
							<% if current_user.id == @book.user_id %>
								<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
								<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
							<% end %>
						</td>
					</tr>
					<!-- 投稿されたcommentを全て表示するindex  -->
					<!-- なぜか表示されない -->
					<!-- eachの範囲内コントローラから受け取った他の値使用できる -->
					<!-- 投稿されたコメントを全て表示するためindex -->
					<% @book.book_comments.each do |book_comment| %>
						<tr>
							<td>
								<%= link_to user_path(@book.user) do %>
									<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
									<br>
									<%= book_comment.user.name %>
								<% end %>
							</td>
							<td>
								<%= book_comment.comment %>

								<!-- 投稿者のみが削除できる -->
								<% if current_user.id == book_comment.user_id %>
									<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn-sm btn-danger destroy_book_#{book_comment.id}" %>
								<% end %>
							</td>
						</tr>
					<% end %>
			</table>
			<!-- comment フォーム -->
							<div>
								<!-- 注意　メンターさんに質問した場所 -->
								<!-- form_forで指定しているので<c.submit でurlしていない> -->
								<%= form_with model: @book_comment_new, url: book_book_comments_path(@book), local: true do |c| %>
									<%= c.text_area :comment, class: "col-xs-9"  %><br>
									<!-- ここ原因 アクションから渡ってくる値が3になっている -->
         							<%= c.submit "Create Comment", method: :post %>
         						<% end %>
							</div>

		</div>
	</div>

</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="container">
	<div class="row">
		<div class="main col-md-offset-3 col-md-6">
			<h1>welcome to<span class="glyphicon glyphicon-book"></span>
				<strong>Bookers</strong>  !!</h1>
				<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
				<p>you can share and exchange your opinions , inpressions , and emotions</p>
				<p>about varioius books!</p>

				<div class="btn-wrapper">
					<div class="row">
						<!-- error ルート名間違い -->
						<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
					</div>
					<div class="row">
						<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
					</div>
				</div>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
              </li>
              <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %>
              </li>
              <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <!-- error原因らしいわからない -->
              <li><%= link_to "  sign up",  new_user_registration_path, class: "glyphicon glyphicon-edit"  %></li>
              <!--  -->
              <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>

    </div>
    <!--画面にheader footer 以外表示されない原因　 -->
    <%= yield %>
  </body>
  <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
</html>

app/views/users/_profile.html.erb
<table class="table">
	<!-- error sytax tr thß-->
	<tr>
		<th><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></th>
	</tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<!-- error -->
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<!-- ここら辺が間違いらしいがわからない -->

			<%= render 'users/profile', user: current_user %>
			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
							<td><%= user.name %></td>
							<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		
	</div>
	
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<!-- コメント件数 -->
						<td>コメント数: <%= @user.book_comments.count %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--books一覧 -->
		</div>
	</div>

</div>